name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install gcc
      run: sudo apt update && sudo apt install -y build-essential
    - name: Compile unit_conversion
      run: |
        ls -l
        if [ ! -f unit_conversion.c ]; then
          echo "Error: unit_conversion.c が見つかりません"
          exit 1
        fi
        gcc unit_conversion.c -o unit_conversion
        chmod +x unit_conversion
    - name: All test
      run: bash -xv ./test.bash
